blank_issues_enabled: false

contact_links:
  - name: 스터디 기록 작성
    url: https://github.com/esc-beep/Terraform-study/issues/new?template=study.md
    about: 학습 내용 기록
  - name: 질문
    url: https://github.com/esc-beep/Terraform-study/issues/new?template=question.md
    about: 학습 중 생긴 궁금증
